### PR TITLE
PMM-2261 Unify common mongod and mongos server metrics

### PR DESCRIPTION
**Pull request by bz2**
New collector_common package for metrics that are the same in both collector_mongod and collector_mongos packages.

The labels of these metrics are now prefixed with just 'mongodb_' rather than 'mongodb_mongo[ds]_'.

Note that because bson only supports ",inline" for maps and structs, the common ServerStatus is embedded by-value not by-pointer.

This PR is about removing duplicated code rather than getting the semantics exactly right. At least MemStats should be split as it has some old storage engine specific values. I'm not keen on including "process" in the metric name, but it would be possible to keep the current layout if that's really needed.

### CODE REVIEW

**Comment by bz2** [comment]
@AlekSi let me know if you want to go over any of the details of this PR.

The  Codacy/PR Quality Review auto review failure is from following the existing naming scheme, am fine to change that but should probably be a separate proposal.

**Comment by bz2** [comment]
I'm happy to rebase this, or park it and have a discussion about what metric names make sense for what exported values.

**Comment by AlekSi** [comment]
Please rebase it.

**Comment by preludedrew** [comment]
According to the changelog, this was added into 0.7.0, but it seems to be missing from the binaries (at least)? I'm still seeing metrics prefixed with mongodb_mongod

**Comment by DexterHD** [comment]
@preludedrew You see it, as namespace was changed only for common metrics. For metrics which differ between `mongod` and `mongos` it remained the same.

For example here is one of common metrics:
```
# HELP mongodb_network_bytes_total The network data structure contains data regarding MongoDB’s network use
# TYPE mongodb_network_bytes_total counter
mongodb_network_bytes_total{state="in_bytes"} 2575
mongodb_network_bytes_total{state="out_bytes"} 68720
```

**Comment by preludedrew** [comment]
@DexterHD Ah, okay I misread it then. Only the common metrics were renamed. I was expecting some dashboards to break, and didn't. I should've dug a little deeper. Thanks for clarifying!

**Comment by Freyert** [comment]
I parsed the AST of this change to generate a list of metrics that changed. I hope this is complete:

```
/mongodb_exporter/collector/common/network.go:23:3:.........|mongo_network_bytes_total
/mongodb_exporter/collector/common/network.go:31:3:.........|mongo_network_metrics_num_requests_total
/mongodb_exporter/collector/common/cursors.go:22:17:........|mongo_cursors
/mongodb_exporter/collector/common/server_status.go:24:16:..|mongo_info
/mongodb_exporter/collector/common/server_status.go:31:3:...|mongo_instance_uptime_seconds
/mongodb_exporter/collector/common/server_status.go:37:3:...|mongo_instance_uptime_estimate_seconds
/mongodb_exporter/collector/common/server_status.go:43:3:...|mongo_instance_local_time
/mongodb_exporter/collector/common/extra_info.go:22:29:.....|mongo_page_faults_total
/mongodb_exporter/collector/common/extra_info.go:28:28:.....|mongo_heap_usage_bytes
/mongodb_exporter/collector/common/memory.go:22:11:.........|mongo_memory
/mongodb_exporter/collector/common/tcmalloc.go:9:3:.........|mongo_tcmalloc_generic_heap
/mongodb_exporter/collector/common/tcmalloc.go:16:3:........|mongo_tcmalloc_pageheap_bytes
/mongodb_exporter/collector/common/tcmalloc.go:23:3:........|mongo_tcmalloc_pageheap_count
/mongodb_exporter/collector/common/tcmalloc.go:30:3:........|mongo_tcmalloc_cache_bytes
/mongodb_exporter/collector/common/tcmalloc.go:37:3:........|mongo_tcmalloc_aggressive_memory_decommit
/mongodb_exporter/collector/common/tcmalloc.go:44:3:........|mongo_tcmalloc_free_bytes
/mongodb_exporter/collector/common/asserts.go:23:3:.........|mongo_asserts_total
/mongodb_exporter/collector/common/conn_pool_stats.go:15:3:.|mongo_connpoolstats_connection_sync
/mongodb_exporter/collector/common/conn_pool_stats.go:22:3:.|mongo_connpoolstats_connections_scoped_sync
/mongodb_exporter/collector/common/conn_pool_stats.go:29:3:.|mongo_connpoolstats_connections_in_use
/mongodb_exporter/collector/common/conn_pool_stats.go:36:3:.|mongo_connpoolstats_connections_available
/mongodb_exporter/collector/common/conn_pool_stats.go:43:3:.|mongo_connpoolstats_connections_created_total
/mongodb_exporter/collector/common/connections.go:22:16:....|mongo_connections
/mongodb_exporter/collector/common/connections.go:30:3:.....|mongo_connections_metrics_created_total
/mongodb_exporter/collector/common/op_counters.go:23:3:.....|mongo_op_counters_total
/mongodb_exporter/collector/common/op_counters.go:32:3:.....|mongo_op_counters_repl_total
```

**Pull request merged**
