### PR TITLE
Add storage stats to collection metrics

### PR DESCRIPTION
**Pull request by masaruhoshi**
Includes additional information about collection stats about "storage".

```
# HELP mongodb_mydb_mycol_storageStats_avgObjSize mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_avgObjSize untyped
mongodb_mydb_mycol_storageStats_avgObjSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 238
# HELP mongodb_mydb_mycol_storageStats_capped mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_capped untyped
mongodb_mydb_mycol_storageStats_capped{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 0
# HELP mongodb_mydb_mycol_storageStats_count mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_count untyped
mongodb_mydb_mycol_storageStats_count{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 57
# HELP mongodb_mydb_mycol_storageStats_freeStorageSize mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_freeStorageSize untyped
mongodb_mydb_mycol_storageStats_freeStorageSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 0
# HELP mongodb_mydb_mycol_storageStats_indexSizes_id mydb.mycol.storageStats.indexSizes.
# TYPE mongodb_mydb_mycol_storageStats_indexSizes_id untyped
mongodb_mydb_mycol_storageStats_indexSizes_id{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 20480
# HELP mongodb_mydb_mycol_storageStats_nindexes mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_nindexes untyped
mongodb_mydb_mycol_storageStats_nindexes{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 1
# HELP mongodb_mydb_mycol_storageStats_scaleFactor mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_scaleFactor untyped
mongodb_mydb_mycol_storageStats_scaleFactor{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 1
# HELP mongodb_mydb_mycol_storageStats_size mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_size untyped
mongodb_mydb_mycol_storageStats_size{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 13591
# HELP mongodb_mydb_mycol_storageStats_storageSize mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_storageSize untyped
mongodb_mydb_mycol_storageStats_storageSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 20480
# HELP mongodb_mydb_mycol_storageStats_totalIndexSize mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_totalIndexSize untyped
mongodb_mydb_mycol_storageStats_totalIndexSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 20480
# HELP mongodb_mydb_mycol_storageStats_totalSize mydb.mycol.storageStats.
# TYPE mongodb_mydb_mycol_storageStats_totalSize untyped
mongodb_mydb_mycol_storageStats_totalSize{cl_id="5f107dfb3a6fc97a81753480",cl_role="shardsvr",collection="mycol",database="mydb",rs_nm="shard-0",rs_state="1"} 40960
```

This is intentionally filtering out any information from `storageStats.wiredTiger` and `storageStats.indexDetails` since it can lead to a high-cardinality issues

```json
db.mycol.aggregate( [ { $collStats: { storageStats: { scale: 1 } } }, { "$project": { "storageStats.wiredTiger": 0, "storageStats.indexDetails": 0 } } ] ).pretty()
{
        "ns" : "mydb.mycol",
        "host" : "localhost:27017",
        "localTime" : ISODate("2021-06-02T02:02:59.173Z"),
        "storageStats" : {
                "size" : 7391055,
                "count" : 48265,
                "avgObjSize" : 153,
                "storageSize" : 4222976,
                "freeStorageSize" : 548864,
                "capped" : false,
                "nindexes" : 3,
                "indexBuilds" : [ ],
                "totalIndexSize" : 5398528,
                "totalSize" : 9621504,
                "indexSizes" : {
                        "_id_" : 2646016,
                        "key_1" : 2183168,
                        "licenseKey_1" : 569344
                },
                "scaleFactor" : 1
        }
}
```

---
- [x] Tests passed.
- [x] Fix conflicts with target branch.
- [x] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

When all checks have passed and code is ready for the review, bot should add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forums](https://forums.percona.com) and [Discord](https://discord.gg/mQEyGPkNbR).

### CODE REVIEW

**Review by percona-csalguero — APPROVED** [review]

**Review by askomorokhov — APPROVED** [review]
Thanks for contributions.
Looks good to me. 👍

**Comment by percona-csalguero** [comment]
Ran the tests manually and all are passing. 
Also I see the metrics: 

```
# HELP mongodb_test_c1_localTime test.c1.
# TYPE mongodb_test_c1_localTime untyped
mongodb_test_c1_localTime{cl_id="60b8cc6dc871fe9be7729427",cl_role="shardsvr",collection="c1",database="test",rs_nm="rs1",rs_state="1"} 1.622725322282e+12
# HELP mongodb_test_c1_storageStats_avgObjSize test.c1.storageStats.
# TYPE mongodb_test_c1_storageStats_avgObjSize untyped
mongodb_test_c1_storageStats_avgObjSize{cl_id="60b8cc6dc871fe9be7729427",cl_role="shardsvr",collection="c1",database="test",rs_nm="rs1",rs_state="1"} 34
# HELP mongodb_test_c1_storageStats_capped test.c1.storageStats.
# TYPE mongodb_test_c1_storageStats_capped untyped
mongodb_test_c1_storageStats_capped{cl_id="60b8cc6dc871fe9be7729427",cl_role="shardsvr",collection="c1",database="test",rs_nm="rs1",rs_state="1"} 0
```
Thanks for the contribution

**Comment by percona-csalguero** [comment]
Hi @masaruhoshi, 
I've created https://github.com/percona/mongodb_exporter/pull/287
Thanks for the help.

**Comment by Aleksa-del** [comment]
@masaruhoshi Hello! We would love to send you a gift from Percona for your contributions. Please, contact us at community-team@percona.com

**Pull request merged**
