### PR TITLE
Add support for timeout offset

### PR DESCRIPTION
**Pull request by mikael-lindstrom**
Allow the MongoDB timeout to be configured relative to the Prometheus scrape timeout. This ensures the Prometheus scrape will get a response even if the exporter cannot connect to MongoDB. Implementation is based on how its done in the [blackbox_exporter](https://github.com/prometheus/blackbox_exporter/blob/2894df6135bda15a8067c85645c7f70e8b1040db/prober/handler.go#L229). This in combination with #624 makes the mongodb_exporter return `mongodb_up 0` when it cannot connect to MongoDB.

I have not been able to verify that `TestGetEncryptionInfo` pass since I cannot get `percona/percona-server-mongodb:5.0.13-1` to start on my M1 Mac (regardless if I use docker-compose or start the image directly).  All other tests pass. 

---

- [ ] Tests passed.
- [ ] Fix conflicts with target branch.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com) or [Discord](https://per.co.na/discord).

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by BupycHuk** [comment]
@mikael-lindstrom could you please update your branch?

**Comment by mikael-lindstrom** [comment]
@BupycHuk Updated the branch now 👍

**Review by ademidoff — APPROVED** [review]

**Comment by JiriCtvrtka** [comment]
@mikael-lindstrom Looks good. Could you also add check when TimeoutOffset is 0 or less? And just show error message. Thank you.

**Comment by mikael-lindstrom** [comment]
I resolved the conflicts and added a check for TimeoutOffset being greater than 0. I also changed the name for the flag from `mongodb.timeout-offset` to `web.timeout-offset` since it's not directly related to MongoDB and it was a bit confusing with the new `mongodb.connect-timeout-ms` flag.

I pushed the latest commit 6 hours ago but for some reason this PR shows "Processing updates". Not sure why but the changes are in my branch.

**Comment by JiriCtvrtka** [comment]
@mikael-lindstrom Could you try to push it once more? Maybe try add just empty commit. Thank you.

**Comment by mikael-lindstrom** [comment]
@JiriCtvrtka Seems to have worked with an empty commit 👍

**Review by JiriCtvrtka — APPROVED** [review]
Great job, thank you.

**Pull request merged**
