### PR TITLE
Add MongoDB Query-comments to .Find() operations

### PR DESCRIPTION
**Pull request by timvaillancourt**
1. Added query comments to .Find() queries in oplog_status.go (only .Find() queries).
2. Cleaned up (terrible) duplicated logic/code for getting oplog timestamps that I made in oplog_status.go long ago.
3. Added a function to shared/utils.go to add code comments (File+LineNum) to MongoDB queries.

Query comment output example in Profiler:

```
test1:PRIMARY> db.system.profile.find({op:"query",ns:{$ne:"local.system.profile"}},{op:1,ns:1,query:1,command:1}).pretty()
{
	"op" : "query",
	"ns" : "local.oplog.rs",
	"query" : {
		"find" : "oplog.rs",
		"sort" : {
			"$natural" : -1
		},
		"skip" : 0,
		"limit" : 1,
		"batchSize" : 1,
		"singleBatch" : true,
		"comment" : "/home/tim/go/src/github.com/percona/mongodb_exporter/collector/mongod/oplog_status.go:90"
	}
}
{
	"op" : "query",
	"ns" : "local.oplog.rs",
	"query" : {
		"find" : "oplog.rs",
		"sort" : {
			"$natural" : 1
		},
		"skip" : 0,
		"limit" : 1,
		"batchSize" : 1,
		"singleBatch" : true,
		"comment" : "/home/tim/go/src/github.com/percona/mongodb_exporter/collector/mongod/oplog_status.go:90"
	}
}
```

### CODE REVIEW

**Comment by AlekSi** [comment]
Why do we need those comments?

**Comment by timvaillancourt** [comment]
@AlekSi query comments show us the source of queries in the MongoDB profiler and .currentOp() outputs. This is very useful for investigation on the server as there is no context logged for operations. The plan is to add this to most mongo-related tools to aid in investigations and isolate user/application operations in profiler/server metrics

**Comment by AlekSi** [comment]
Is that approach documented somewhere?

**Comment by timvaillancourt** [comment]
Yes, this is documented here: https://docs.mongodb.com/v3.2/reference/method/cursor.comment/.

It is as simple as adding a .Comment(<string>) function to any mongo query object. In pymongo (python) it is lower-case .comment(<string>).

**Pull request merged**
