### PR TITLE
Build against latest version of prometheus golang-client

### PR DESCRIPTION
**Pull request by jlemaes**
This pull request works again with the latest version of prometheus golang-client where in [this commit](https://github.com/prometheus/client_golang/commit/2fee50beaa152342e8347c41edf2202c3bd5f858) the counter.Set method was removed.

### CODE REVIEW

**Comment by timvaillancourt** [comment]
Thanks @jlemaes for this change. Matching the new prometheus_client is the inevitable way forward.

I'll run this through some testing and if that is successful, this can be approved.

**Comment by xose** [comment]
We have started using the exporter with this pull request applied on a new MongoDB cluster. It worked fine until ~5 minutes after we started inserting data, when all `mongos` metrics collection stopped.

The collectors pointing to the `mongos` daemons now return a 500 error with the following message:

```
An error has occurred during metrics collection:

6 error(s) occurred:
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"moveChunk.from_failed" > counter:<value:4 >  was collected before with the same name and label values
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"moveChunk.from" > counter:<value:3 >  was collected before with the same name and label values
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"multi-split" > counter:<value:18 >  was collected before with the same name and label values
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"moveChunk.start" > counter:<value:7 >  was collected before with the same name and label values
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"moveChunk.to" > counter:<value:3 >  was collected before with the same name and label values
* collected metric mongodb_mongos_sharding_changelog_10min_total label:<name:"event" value:"moveChunk.commit" > counter:<value:3 >  was collected before with the same name and label values
```

There are no errors or warnings on the collector log files. Restarting the collector results in the same error.

Metrics for `mongod` processes work fine, it's just `mongos` that fail.

**Comment by jlemaes** [comment]
There was a bug in the code that should be fixed now thanks to @mathieuhinderyckx. I don't have time to test this against a mongos cluster. Can you please try again?

**Comment by dbmurphy** [comment]
This will need to wait a week or two as we are currently code locked for a new PMM release (currently in beta)

**Comment by xose** [comment]
I have applied the latest commits and the exporter is working fine now, even during chunk migrations.

**Comment by timvaillancourt** [comment]
I've seen no issues in the testing of this PR. We will merge this soon

**Comment by rnovikovP** [comment]
Hello  @jlemaes  ,  please sing Percona CLA so we can merge your PR

Thanks for Contributing!

**Comment by kinghrothgar** [comment]
Any update on when this might get merged? I was putting off using this exporter until this and #52 are merged.

**Comment by AlekSi** [comment]
Can you please resolve merge conflicts?

**Comment by AlekSi** [comment]
Original reported issues is solved by #67.

**Pull request closed without merging**
