### PR TITLE
Finegrained index usage and coll stats err handling

### PR DESCRIPTION
**Pull request by akira-kurogane**
This is a patch to enable index usage ($indexStats) and collection status ($collStats) metrics to continue being gathered when some collections succeed whilst others fail. (The current behaviour is that the routine will exit the function at first error without trying any more collections, and it appends no stats at all into the running collection round.)

I mainly think of it this as an alternative pull request #122, but I suppose it could also be complimentary.

Any user with authentication enabled will encounter authorization errors, regardless of which inbuilt role they may use (excluding the superuser roles root or \_\_system, which monitoring clearly shouldn't use), so this patch is required to make the optional -collect.indexusage and -collect.collection modes work.

Logging: this patch logs which collections failed. To avoid log being filled up too much extra logic has been added on top of that to only print each type of error once.

Example stdout log output with -collect.indexusage for the case of an "admin" user with maximum privileges with inbuilt (but not super-user) roles:
```text
~]$ export MONGODB_URI='mongodb://admin:xxxx@hostxxx/admin'
~]$ ./mongodb_exporter -collect.indexusage
INFO[0000] collecting index stats                        source="index_usage.go:62"
ERRO[0000] Failed to collect index stats for collection admin.system.keys. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection admin.system.profile. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection admin.system.users. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection admin.system.version. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection config.system.sessions. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.profile. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.replset. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.rollback.id. This log message will be suppressed from now.  source="index_usage.go:90"
INFO[0000] Starting HTTP server for http://:9216/metrics ...  source="server.go:121"
```

Example for -collect.indexusage with a non-admin user which had a mixed bag of permissions issues.
```text
~]$ export MONGODB_URI='mongodb://admin:xxxx@hostxxx/admin'
~]$ ./mongodb_exporter -collect.indexusage -web.listen-address :17099
INFO[0000] collecting index stats                        source="index_usage.go:62"
ERRO[0000] Failed to get a list of collection names for db=admin. Index usage stats will not be collected for this db. This log message will be suppressed from now.  source="index_usage.go:78"
ERRO[0000] Failed to get a list of collection names for db=compBuilder. Index usage stats will not be collected for this db. This log message will be suppressed from now.  source="index_usage.go:78"
ERRO[0000] Failed to collect index stats for collection config.system.sessions. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.profile. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.replset. This log message will be suppressed from now.  source="index_usage.go:90"
ERRO[0000] Failed to collect index stats for collection local.system.rollback.id. This log message will be suppressed from now.  source="index_usage.go:90"
INFO[0000] Starting HTTP server for http://:17099/metrics ...  source="server.go:121"
```

The messages for -collect.collection mode are equivalent of course.

### CODE REVIEW

**Comment by akira-kurogane** [comment]
FWIW it's worth this is going OK in real cluster I've deployed it to. Only regret is I did not remove the following line from index_usage.go:
```go
log.Info("collecting index stats")
```
That causes pointless log bloat.

**Comment by DexterHD** [comment]
> FWIW it's worth this is going OK in real cluster I've deployed it to. Only regret is I did not remove the following line from index_usage.go:
> 
> ```go
> log.Info("collecting index stats")
> ```
> 
> That causes pointless log bloat.

Hi. You can remove it and I think I can approve and merge this PR :)

**Comment by akira-kurogane** [comment]
> Hi. You can remove _(that log.Info())_ and I think I can approve and merge this PR :)

Hi @DexterHD. Done, that tweak is merged into this PR.

**Comment by DexterHD** [comment]
@AlekSi I don't why, but Codacy seems to stuck. Maybe problem is I'm not a member of organization on Codacy?

**Comment by akira-kurogane** [comment]
> @AlekSi I don't why, but Codacy seems to stuck. Maybe problem is I'm not a member of organization on Codacy?

I'm afraid I don't know. Several hours to overnight for completion has been the usual amount in my experience.

**Comment by AlekSi** [comment]
@DexterHD That status check is not required, so feel free to merge this PR. Probably we will remove it completely.

**Comment by MajorBreakfast** [comment]
With this solution I still see the unauthorized logs once in the exporter the first time they appear and every time in the logs of MongoDB itself (unless I grant the `root` and `__system` roles to the user). The latter is what brought me to this PR because our logs are currently filled them. Is there already a known solution to get rid of them? Can #122 get rid of all warnings?

**Comment by akira-kurogane** [comment]
Hi @MajorBreakfast 

Yes, this patch (pull request 128) is a one-sided log suppression. It only stops log bloat in the mongodb_exporter log. It keeps on trying the command each time so the mongod will log authorization errors if the mongodb_exporter user is indeed unauthorized.

If it is _only_ the system collections that you are seeing the mongod log messages from then pull request 122's patch would fix the issue for you.

Please share the log messages so we can be sure. It may be something else. For known issues at least I am aware of a considerable log bloat issue when collStats is run against a _mongos_ node. https://jira.percona.com/browse/PMM-4806

**Comment by MajorBreakfast** [comment]
@akira-kurogane Thanks for your fast response

I'm using the `bitnami/mongodb-exporter:0.10.0-r36` and the `mongo:4.2.0` container images which was built two days ago according to dockerhub.

Here the logs if I use my admin user which has the `root` role:
```
# Loaded metrics page for the first time
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.206+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:42502 #2 (2 connections now open)
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.207+0000 I  NETWORK  [conn2] received client metadata from 127.0.0.1:42502 conn2: { driver: { name: "mongo-go-driver", version: "v1.1.1" }, os: { type: "linux", architecture: "amd64" }, platform: "go1.12.9", application: { name: "mongodb_exporter" } }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.244+0000 I  ACCESS   [conn2] Successfully authenticated as principal admin on admin from client 127.0.0.1:42502
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.319+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.users", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo-exporter time="2019-10-29T08:13:27Z" level=error msg="(Unauthorized) not authorized on admin to execute command { aggregate: \"system.users\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"6c1effcb-e8f3-475d-852a-77dcb854a872\") }, $db: \"admin\" }. Index usage stats will not be collected for this collection. This log message will be suppressed from now." source="index_usage.go:104"
mongo-8467f588c5-r5597 mongo-exporter time="2019-10-29T08:13:27Z" level=error msg="(Unauthorized) not authorized on admin to execute command { aggregate: \"system.version\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"6c1effcb-e8f3-475d-852a-77dcb854a872\") }, $db: \"admin\" }. Index usage stats will not be collected for this collection. This log message will be suppressed from now." source="index_usage.go:104"
mongo-8467f588c5-r5597 mongo-exporter time="2019-10-29T08:13:27Z" level=error msg="(Unauthorized) not authorized on config to execute command { aggregate: \"system.sessions\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"6c1effcb-e8f3-475d-852a-77dcb854a872\") }, $db: \"config\" }. Index usage stats will not be collected for this collection. This log message will be suppressed from now." source="index_usage.go:104"
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.324+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.version", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:27.327+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "config" }

# Loaded metrics page for the second time
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:31.765+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.users", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:31.766+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.version", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:31.768+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "config" }

# Loaded metrics page for the third time
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:34.631+0000 I  COMMAND  [conn2] command admin appName: "mongodb_exporter" command: dbStats { dbStats: 1, scale: 1, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" } numYields:0 reslen:262 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 1 } }, ReplicationStateTransition: { acquireCount: { w: 1 } }, Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 3 } }, Mutex: { acquireCount: { r: 1 } } } storage:{} protocol:op_msg 110ms
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:34.697+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.users", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:34.698+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.version", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:34.703+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "config" }

# Loaded metrics page for the forth time
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:49.431+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.users", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:49.440+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { aggregate: "system.version", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "admin" }
mongo-8467f588c5-r5597 mongo 2019-10-29T08:13:49.444+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("6c1effcb-e8f3-475d-852a-77dcb854a872") }, $db: "config" }
```

With a user which has the roles `{ role: "clusterMonitor", db: "admin" },  { role: "read", db: "local" }`:
```
# Loaded metrics page for the first time
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.122+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:45912 #2 (2 connections now open)
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.123+0000 I  NETWORK  [conn2] received client metadata from 127.0.0.1:45912 conn2: { driver: { name: "mongo-go-driver", version: "v1.1.1" }, os: { type: "linux", architecture: "amd64" }, platform: "go1.12.9", application: { name: "mongodb_exporter" } }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.214+0000 I  ACCESS   [conn2] Successfully authenticated as principal mongodb_exporter on admin from client 127.0.0.1:45912
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.244+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo-exporter time="2019-10-29T08:22:48Z" level=error msg="(Unauthorized) not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID(\"d3630be3-e978-461a-a494-0ee2e79092c5\") }, $db: \"admin\" }. Collection stats will not be collected for this db. This log message will be suppressed from now." source="collections_status.go:146"
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.260+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { collStats: "system.sessions", scale: 1, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }
mongo-7cfcc75964-wfdpj mongo-exporter time="2019-10-29T08:22:48Z" level=error msg="(Unauthorized) not authorized on config to execute command { collStats: \"system.sessions\", scale: 1, lsid: { id: UUID(\"d3630be3-e978-461a-a494-0ee2e79092c5\") }, $db: \"config\" }. Collection stats will not be collected for this collection. This log message will be suppressed from now." source="collections_status.go:169"
mongo-7cfcc75964-wfdpj mongo-exporter time="2019-10-29T08:22:48Z" level=error msg="(Unauthorized) not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID(\"d3630be3-e978-461a-a494-0ee2e79092c5\") }, $db: \"admin\" }. Index usage stats will not be collected for this db. This log message will be suppressed from now." source="index_usage.go:80"
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.282+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo-exporter time="2019-10-29T08:22:48Z" level=error msg="(Unauthorized) not authorized on config to execute command { aggregate: \"system.sessions\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"d3630be3-e978-461a-a494-0ee2e79092c5\") }, $db: \"config\" }. Index usage stats will not be collected for this collection. This log message will be suppressed from now." source="index_usage.go:104"
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:48.285+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }

# Loaded metrics page for the second time
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:51.887+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:51.901+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { collStats: "system.sessions", scale: 1, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:51.932+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:51.968+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }

# Loaded metrics page for the third time
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:55.266+0000 I  COMMAND  [conn2] command admin appName: "mongodb_exporter" command: dbStats { dbStats: 1, scale: 1, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" } numYields:0 reslen:262 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 1 } }, ReplicationStateTransition: { acquireCount: { w: 1 } }, Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 3 } }, Mutex: { acquireCount: { r: 1 } } } storage:{} protocol:op_msg 104ms
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:55.286+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:55.296+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { collStats: "system.sessions", scale: 1, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:55.314+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:55.326+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }

# Loaded metrics page for the forth time
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:58.076+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:58.083+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { collStats: "system.sessions", scale: 1, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:58.100+0000 I  ACCESS   [conn2] Unauthorized: not authorized on admin to execute command { listCollections: 1, filter: {}, nameOnly: true, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "admin" }
mongo-7cfcc75964-wfdpj mongo 2019-10-29T08:22:58.108+0000 I  ACCESS   [conn2] Unauthorized: not authorized on config to execute command { aggregate: "system.sessions", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID("d3630be3-e978-461a-a494-0ee2e79092c5") }, $db: "config" }
```

**Comment by akira-kurogane** [comment]
Hi @MajorBreakfast 

We can't see the _"mongos collstats doesn't know about: xxxx"_ messages, so I can relax knowing this isn't a case of Percona's [PMM-4806](https://jira.percona.com/browse/PMM-4806) => MongoDB's [SERVER-36801](https://jira.mongodb.org/browse/SERVER-36801).The log bloat from that can be pretty large.

I see that you are hitting the authorization rejections only on the system collections, so the proposed pull request 122 would in fact stop these log messages from appearing. Because it would stop the collector from iterating the admin, config and local dbs completely for collStats and $indexStats metrics collection.

Reading the descriptions of [root](https://docs.mongodb.com/manual/reference/built-in-roles/#root) and [clusterMonitor](https://docs.mongodb.com/manual/reference/built-in-roles/#clusterMonitor) they shouldn't be failing, but maybe the documentation isn't being clear about system collections access. And maybe the new collections for sessions and transactions are a new exception on top of that.

I am also seeing listCollections fail for the first time with these roles. It may be something related to the new-in-4.0 nameOnly + authorizedCollections options of the [listCollections](https://docs.mongodb.com/manual/reference/command/listCollections/index.html), which I deduce are used when you run "show collections" in 4.2 (maybe 4.0) mongo shell.

Also I want to point out that the user must be created on all the shards, if this is a cluster. Creating the user via the mongos node creates it on the configsvr replicaset, but that is not copied to shards as well. So for admin and monitoring and backup users we as MongoDB DBAs must run the same db.createUser(...) command once for each shard too. And update password, grant roles, etc.

There's a few different things mentioned to this point. 1) I have a slight worry you didn't run createUser / grantRolesToUser to the shards as well if this is cluster, although that doesn't seem right because you have observed changes, 2) looks like permissions changes for listCollections are possibly making things worse, 3) if nothing else we may find that no inbuilt user with the maximum permissions a monitoring user should have can run collStats, $indexStats on any collection so we should come back to pull request 122 to avoid the issue. Please let me know what you can confirm / think about the above.

**Comment by MajorBreakfast** [comment]
Here's are the minimal Kubernetes manifests I created to reproduce the "unauthorized" logs:

deployment.yml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-mongo
  template:
    metadata:
      labels:
        app: my-mongo
    spec:
      containers:
        - name: mongo-exporter
          image: bitnami/mongodb-exporter:0.10.0-r36
          args:
            - --collect.collection
            - --collect.database
            - --collect.indexusage
            - --collect.topmetrics
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: MONGODB_URI
              value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@localhost:27017
        - name: mongo
          image: mongo:4.2.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: mongo-persistent-storage
```

secret.yml
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-credentials
data:
  username: YWRtaW4= # admin
  password: Y2hhbmdlaXQ= # changeit
```

To reproduce the "unauthorized" logs I deployed these resources into Kubernetes for Docker desktop via  `kubectl apply -f .`. Then, I tailed the logs of all containers via `stern .`.

**Comment by akira-kurogane** [comment]
So I gather that is the mongo image from https://hub.docker.com/_/mongo, which looks to be a standalone. If so don't worry about the possibility # 1 in my list above, i.e. of the shards in a cluster not having the user created on them.

Container definitions are getting off-topic for mongodb_exporter. I'm not going to work with that.

But I can reproduce the same errors using 4.2.0 replicaset, connecting with a user that has only the clusterMonitor role granted to it.
That is:
* **listCollections access control rejection on admin db**: _"Unauthorized: not authorized on admin to execute command { listCollections: 1 ..."_ message appears in the mongod's log file **every** time the mongodb_exporter does collection (not just first time)
* **collStats access control rejection on apparently all system collections**: _"Unauthorized: not authorized on [config|local] to execute command { collStats: "system.xxxx..."_ messages appear in the mongod log file **every** time the mongodb_exporter does collection (not just first time). It seems to be for many but I expect not all the system collections. It is both config and local, and I think it would be admin too if the listCollections command didn't faile
* **$indexStats access control rejection on the same system collections as collStats error**: _"Unauthorized: not authorized on local to execute command { aggregate: "system.rollback.id", pipeline: \[ \{ $indexStats: \{\} \} ..."_ messages appear in the mongod log file **every** time the mongodb_exporter does collection (not just first time).

I think that there are two issues

1. listCollections command needs an update to use the "authorizedCollections" option (as well as the "nameOnly" one).
2. "clusterMonitor" role users haven't been given permissions to run collStats and $indexStats for the system collections because I suspect MongoDB doesn't see the point in monitoring them themselves. These are collections that are made and handled by code in the program; they must be optimized or they would cause performance regressions noticed by MongoDB build team before releases. Some of them are single doc collections that are little-accessed. Some of them may are heavily used but it is necessary background cost that is smaller and proportional to the user load. So monitoring of just the collections that "clusterMonitor" already covers is the right thing to do.

Fixing 1 means all lines like `c, err := client.Database(db).ListCollections(context.TODO(), bson.M{}, options.ListCollections().SetNameOnly(true))` in mongodb_exporter should be updated.
Fixing 2.  means - don't attempt to run collStats and $indexStats on system collections = apply PR 122.

If the fix for 2 applies a blanket rule of not running collStats at all in "admin" or "config" then we wont have to fix 1.

Let's open a new issue for 1 above and reopen pull request 122 for issue 2.

**Comment by akira-kurogane** [comment]
Created https://jira.percona.com/browse/PMM-4906 for the "1" issue mentioned in the comment above. Please add any further comments on that issue there.

See #122 (and https://jira.percona.com/browse/PMM-4541) for the "2" issue mentioned above.

**Pull request merged**
