### PR TITLE
Fix for broken labels on index_usage metrics

### PR DESCRIPTION
**Pull request by akira-kurogane**
The index stats lacked db as a label. I.e. a "foo" collection's stats from databases "x" and "y" would have been indistinct, or one overwriting the other. This fixes that.

### CODE REVIEW

**Comment by AlekSi** [comment]
>  I.e. a "foo" collection's stats from databases "x" and "y" would have been indistinct, or one overwriting the other.

Aren't current code adds database name as a prefix for collection name?

**Comment by akira-kurogane** [comment]
Ah, so it does! Maybe I removed db name by mistake while debugging why I wasn't getting any results, which was ultimately the issue in pull request #122.

I thought "db + . +  collectionName" was my temporary work, and then I polished that some more by making db a separate label as is done for collector/mongod/collections_status.go.

If you like the separated db label, then this patch. If not, no need for this patch then I guess.

**Comment by rnovikovP** [comment]
my 2c:  to aggregate data  by labels will be simpler than "cut" it by "."
So even if this will require to do some dashboards changes - it's better to have these parameters separated

**Comment by klynch** [comment]
+1 on merging this!

**Comment by klynch** [comment]
@AlekSi Any chance this can get merged and we can get a release? I'm running into this issue and may end up cutting a release from this branch.

**Comment by AlekSi** [comment]
> If you like the separated db label, then this patch. If not, no need for this patch then I guess.

Is there a case where you want to aggregate by collection name, but not by database name / "full" collection name?

**Comment by AlekSi** [comment]
Ok, I will merge this. Aggregating by database name makes sense.

**Comment by AlekSi** [comment]
Thank you!

**Comment by akira-kurogane** [comment]
My pleasure.

**Pull request merged**
