### PR TITLE
PMM-6089 Update go.mod.

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by tetianakravchenko** [comment]
any chance to get a new release with this change?

**Comment by rnovikovP** [comment]
@tetianakravchenko ,  do you use Exporter separately or with PMM?

**Comment by tetianakravchenko** [comment]
@rnovikovP I'm using mongodb-exporter separately, and with latest binary `v0.11.0` I'm getting the issue, described in this issue: https://jira.percona.com/browse/PMM-4829

**Comment by rnovikovP** [comment]
@tetianakravchenko , just checked with a Dev team. Considering the importance and need for this fix we'll try to do a release on Monday.

**Comment by tetianakravchenko** [comment]
@rnovikovP thank you for such a quick response and release!

**Pull request merged**
