### PR TITLE
Removed repeated `Build the exporter`

### PR DESCRIPTION
**Pull request by AATHITH**
Removed `Build the exporter` content that is repeated twice in the README file

When all checks have passed and the code is ready for review, please add `pmm-review-exporters` as the reviewer. That would assign people from the review team automatically.

### CODE REVIEW

**Comment by AlekSi** [comment]
@denisok PTAL

**Comment by denisok** [comment]
Thanks @AATHITH for this PR. Recomended way is to add `pmm-review-exporters` team to get PR reviewed and landed.

**Review by denisok — APPROVED** [review]

**Comment by AlekSi** [comment]
External people like me or @AATHITH can't assign reviewers – there is no button for that

**Comment by denisok** [comment]
@AlekSi aha... interesting, will check what we could do here.

**Comment by denisok** [comment]
@AlekSi we probably would add gh action to assign team if checks passed and code is ready for merge. Thanks for the noticing!

**Review by JiriCtvrtka — APPROVED** [review]

**Pull request merged**
