### PR TITLE
Fixed TLS skip verify host issue

### PR DESCRIPTION
**Pull request by akoutmos**
This fixed the issue where when given the `--mongodb.tls-disable-hostname-validation` flag hostname validation was still occurring.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/mongodb_exporter?pullRequest=156) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/mongodb_exporter?pullRequest=156) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/mongodb_exporter?pullRequest=156) it.</sub>

**Comment by rnovikovP** [comment]
Hi @akoutmos Thanks for your fix! 
Can you click CLA button ^^ and add some tests to cover this problem you fixed.

**Comment by akoutmos** [comment]
Will do Roma. I should have some spare cycles this weekend to add tests to cover that.

**Comment by DexterHD** [comment]
@akoutmos Hi, sorry for the late feedback. I think it's not necessary to change that line because seems code works correctly. As you can see:

https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/shared/connection.go#L148-L153

We are using:

https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/shared/connection.go#L149

and this function set DNS name to empty:

https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/shared/connection.go#L164-L169

So DNS check becomes turned off.

Here is how you can check that this flag works fine in current state:
- Go to `./scripts/ssl.sh` and replace `/CN=localhost` to something else like `/CN=test.com`. (It is script for generating test certificates for test mongo instance).
- Go to project root and run `./scripts/ssl.sh`. It regenerates certificates located in `./testdata` (Which is used inside docker. See `docker-compose.yml`).
- Replace `--sslMode=preferSSL` to `--sslMode=requireSSL` in `docker-compose.yml` and run `docker-compose up -d` to start testing mongo instance inside the docker.
- Build `mongodb_exporter` with `make release` command.
- Run it such like this: `./bin/mongodb_exporter --mongodb.tls --mongodb.tls-cert=./testdata/client.pem --mongodb.tls-ca=./testdata/ca.crt --mongodb.uri=mongodb://localhost:27017/admin`. You will have got an error like: `ERRO[0000] Could not connect to localhost:27017. Got: x509: certificate is valid for test.com, not localhost`
- Then add `--mongodb.tls-disable-hostname-validation` parameter and try to start `mongodb_exporter` again. It will have run successfully. I\ve just checked it in my dev environment.

I suppose that you may have some problems on your side? Maybe you can give me more information about your certs and environment and we can solve your problem together?

**Comment by akoutmos** [comment]
Interesting. Perhaps the combination of cli flags that I sent caused an issue then? I'll try and repro the issue using master and see what happens. Thanks for the feedback

**Comment by DexterHD** [comment]
> Interesting. Perhaps the combination of cli flags that I sent caused an issue then? I'll try and repro the issue using master and see what happens. Thanks for the feedback

It would be great if you can reproduce this, to see what exactly happens! Also, give me please feedback when you will have done it.

**Comment by akoutmos** [comment]
I'll try and get to it by end of week this week

**Comment by DexterHD** [comment]
Fixed in [v0.10.0](https://github.com/percona/mongodb_exporter/releases/tag/v0.10.0).

**Pull request closed without merging**
