### PR TITLE
Collector for working with data from the system profile

### PR DESCRIPTION
**Pull request by mikle7771**
This implementation allows you to get metrics on slow queries.

```
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="admin",rs_state="2"} 1
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="config",rs_state="2"} 3
mongodb_profile_slow_query_count{cl_id="58ffb6f25ee88911bb439499",cl_role="",database="local",rs_state="2"} 0
```

--collector.profile-time-ts=30 Set time for scrape slow queries. This interval must be synchronized with the Prometheus scrape interval

For the collector to work, you must enable the profiler
https://www.mongodb.com/docs/manual/tutorial/manage-the-database-profiler/

This PR implements the functionality from this issue https://github.com/percona/mongodb_exporter/issues/707
---

- [ ] Tests passed.
- [ ] Fix conflicts with target branch.

### CODE REVIEW

**Review by tregubov-av — APPROVED** [review]
Thank you!
I think I like to it.

**Review by BupycHuk — APPROVED** [review]
looks good to me. Should we add to documentation how to enable profile?

**Comment by mikle7771** [comment]
> looks good to me. Should we add to documentation how to enable profile?

Where is the best place to describe this?

**Comment by BupycHuk** [comment]
@mikle7771 I think somewhere [here](https://github.com/percona/mongodb_exporter/blob/main/README.md#enabling-collstats-metrics-gathering) will be ok

**Comment by mikle7771** [comment]
> @mikle7771 I think somewhere [here](https://github.com/percona/mongodb_exporter/blob/main/README.md#enabling-collstats-metrics-gathering) will be ok

Done

**Review by BupycHuk — APPROVED** [review]

**Review by atymchuk — APPROVED** [review]

**Comment by tregubov-av** [comment]
👍

**Pull request merged**
