### PR TITLE
Fix AuthSource initialization from URI

### PR DESCRIPTION
**Pull request by a-gavin**
Note that I did not implement initialization of `clientOptions.Auth.AuthMechanism` or `clientOptions.Auth.AuthMechanismProperties` when `clientOptions.Auth` returned by `ApplyURI()` is nil

### CODE REVIEW

**Comment by a-gavin** [comment]
Updated changes with output of ``gofumpt -w -l ...``

**Comment by a-gavin** [comment]
The CI tests for 1.17.x mongo:5.0 and 1.17.x percona/percona-server-mongodb:4.4 appear to be existing pipeline and unrelated to this PR. The 1.17.x mongo:4.4 test does appear related so I am investigating that.

**Comment by a-gavin** [comment]
Tests for go v1.17 with Mongo 4.4 (aside from the ``... collected before with the same name and label values`` failures which exist on other PRs) are passing on my local when following the [CONTRIBUTING.md](https://github.com/percona/mongodb_exporter/blob/main/CONTRIBUTING.md#tests) docs and associated setup.

Setup for tests:
```console
% go version
go version go1.17 linux/amd64
% git log -1              
commit c18ef0368b5bdcff3cc386314d4018576ebaaa70 (HEAD -> fix_uri_parsing)
Author: Alex Gavin <a_gavin@icloud.com>
Date:   Thu Jul 28 00:45:52 2022 -0700

    Fix AuthSource initialization from URI
% make  test-cluster-clean
docker-compose down --remove-orphans
Removing network mongodb_exporter_git_default
WARNING: Network mongodb_exporter_git_default not found.
% TEST_MONGODB_IMAGE=mongo:4.4 make test-cluster

docker-compose up -d
Creating network "mongodb_exporter_git_default" with the default driver
Creating mongo-2-2       ... done
Creating mongo-1-2       ... done
Creating mongo-2-3       ... done
Creating mongo-cnf-3     ... done
Creating mongo-1-arbiter ... done
Creating mongo-2-arbiter ... done
Creating mongo-cnf-2     ... done
Creating standalone      ... done
Creating mongo-1-3       ... done
Creating mongo-2-1       ... done
Creating mongo-1-1       ... done
Creating mongo-cnf-1     ... done
Creating mongo-rs2-setup ... done
Creating mongo-rs1-setup ... done
Creating mongo-cnf-setup ... done
Creating mongos          ... done
Creating mongo-shard-setup ... done
% 
```

Specific `TestConnect` output (run from within the `src/exporter` directory:
```console
% go test -v -run TestConnect                   
=== RUN   TestConnect
=== RUN   TestConnect/Connect_without_SSL
=== RUN   TestConnect/Test_per-request_connection
=== RUN   TestConnect/Test_global_connection
--- PASS: TestConnect (0.11s)
    --- PASS: TestConnect/Connect_without_SSL (0.02s)
    --- PASS: TestConnect/Test_per-request_connection (0.07s)
    --- PASS: TestConnect/Test_global_connection (0.02s)
PASS
ok      github.com/percona/mongodb_exporter/exporter    0.116s
% go test -race -v -timeout 30s -run TestConnect
=== RUN   TestConnect
=== RUN   TestConnect/Connect_without_SSL
=== RUN   TestConnect/Test_per-request_connection
=== RUN   TestConnect/Test_global_connection
--- PASS: TestConnect (0.29s)
    --- PASS: TestConnect/Connect_without_SSL (0.03s)
    --- PASS: TestConnect/Test_per-request_connection (0.17s)
    --- PASS: TestConnect/Test_global_connection (0.09s)
PASS
ok      github.com/percona/mongodb_exporter/exporter    0.342s
```

Full test output:
```console
% make test
go test -v -count 1 -timeout 30s ./...
=== RUN   TestBuildExporter
time="2022-08-15T10:31:27-07:00" level=debug msg="Compatible mode: true"
time="2022-08-15T10:31:27-07:00" level=debug msg="Connection URI: mongodb://usr:pwd@127.0.0.1/"
--- PASS: TestBuildExporter (0.00s)
PASS
ok  	github.com/percona/mongodb_exporter	0.015s
=== RUN   TestCollStatsCollector
--- PASS: TestCollStatsCollector (0.14s)
=== RUN   TestListDatabases
=== RUN   TestListDatabases/Empty_filter_in_list
=== RUN   TestListDatabases/One_collection_in_list
=== RUN   TestListDatabases/Multiple_namespaces_in_list
--- PASS: TestListDatabases (0.29s)
    --- PASS: TestListDatabases/Empty_filter_in_list (0.00s)
    --- PASS: TestListDatabases/One_collection_in_list (0.00s)
    --- PASS: TestListDatabases/Multiple_namespaces_in_list (0.00s)
=== RUN   TestListCollections
=== RUN   TestListCollections/Basic_test
=== RUN   TestListCollections/Filter_in_databases
=== RUN   TestListCollections/With_namespaces_list
=== RUN   TestListCollections/Empty_namespaces_list
=== RUN   TestListCollections/Count_basic
=== RUN   TestListCollections/Filtered_count
--- PASS: TestListCollections (0.31s)
    --- PASS: TestListCollections/Basic_test (0.00s)
    --- PASS: TestListCollections/Filter_in_databases (0.00s)
    --- PASS: TestListCollections/With_namespaces_list (0.00s)
    --- PASS: TestListCollections/Empty_namespaces_list (0.00s)
    --- PASS: TestListCollections/Count_basic (0.00s)
    --- PASS: TestListCollections/Filtered_count (0.00s)
=== RUN   TestSplitNamespace
--- PASS: TestSplitNamespace (0.00s)
=== RUN   TestDBStatsCollector
--- PASS: TestDBStatsCollector (0.13s)
=== RUN   TestDebug
--- PASS: TestDebug (0.00s)
=== RUN   TestDiagnosticDataCollector
--- PASS: TestDiagnosticDataCollector (0.05s)
=== RUN   TestAllDiagnosticDataCollectorMetrics
--- PASS: TestAllDiagnosticDataCollectorMetrics (0.09s)
=== RUN   TestContextTimeout
--- PASS: TestContextTimeout (3.76s)
=== RUN   TestDisconnectedDiagnosticDataCollector
--- PASS: TestDisconnectedDiagnosticDataCollector (0.03s)
=== RUN   TestConnect
=== RUN   TestConnect/Connect_without_SSL
=== RUN   TestConnect/Test_per-request_connection
=== RUN   TestConnect/Test_global_connection
--- PASS: TestConnect (0.09s)
    --- PASS: TestConnect/Connect_without_SSL (0.03s)
    --- PASS: TestConnect/Test_per-request_connection (0.04s)
    --- PASS: TestConnect/Test_global_connection (0.02s)
=== RUN   TestMongoS
time="2022-08-15T10:31:32-07:00" level=error msg="cannot get replSetGetStatus: replSetGetStatus is not supported through mongos"
--- PASS: TestMongoS (0.01s)
=== RUN   TestMongoUp
time="2022-08-15T10:31:32-07:00" level=error msg="Cannot connect to MongoDB: invalid MongoDB options: error parsing uri: invalid host \"127.0.0.1:123456\": port must be in the range [1, 65535]"
--- PASS: TestMongoUp (0.00s)
=== RUN   TestGeneralCollector
time="2022-08-15T10:31:32-07:00" level=error msg="error while checking mongodb connection: client is disconnected. mongo_up is set to 0"
--- PASS: TestGeneralCollector (0.03s)
=== RUN   TestIndexStatsCollector
--- PASS: TestIndexStatsCollector (0.30s)
=== RUN   TestDescendingIndexOverride
--- PASS: TestDescendingIndexOverride (0.44s)
=== RUN   TestSanitize
=== RUN   TestSanitize/With_building
=== RUN   TestSanitize/Without_building
--- PASS: TestSanitize (0.00s)
    --- PASS: TestSanitize/With_building (0.00s)
    --- PASS: TestSanitize/Without_building (0.00s)
=== RUN   TestMetricName
--- PASS: TestMetricName (0.00s)
=== RUN   TestPrometeusize
--- PASS: TestPrometeusize (0.00s)
=== RUN   TestMakeRawMetric
--- PASS: TestMakeRawMetric (0.00s)
=== RUN   TestRawToCompatibleRawMetric
--- PASS: TestRawToCompatibleRawMetric (0.00s)
=== RUN   TestReplsetStatusCollector
--- PASS: TestReplsetStatusCollector (0.03s)
=== RUN   TestReplsetStatusCollectorNoSharding
--- PASS: TestReplsetStatusCollectorNoSharding (0.00s)
=== RUN   TestSecondaryLag
    secondary_lag_test.go:72: This is failing in GitHub actions. Cannot make secondary to lag behind
--- SKIP: TestSecondaryLag (0.00s)
=== RUN   TestServerStatusDataCollector
    serverstatus_collector_test.go:59: 
        	Error Trace:	serverstatus_collector_test.go:59
        	Error:      	Received unexpected error:
        	            	gathering metrics failed: 50 error(s) occurred:
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:1024 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:4096 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:16384 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:65536 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:262144 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:1.048576e+06 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:4.194304e+06 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:1.6777216e+07 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:6.7108864e+07 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:2.68435456e+08 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:1.073741824e+09 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_lowerBound" { untyped:<value:2 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_lowerBound" { untyped:<value:4 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_lowerBound" { untyped:<value:8 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_lowerBound" { untyped:<value:16 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_lowerBound" { untyped:<value:32 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicNumPlans_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:128 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:256 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:512 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:1024 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:2048 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:4096 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:8192 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:16384 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_lowerBound" { untyped:<value:32768 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicWorks_count" { counter:<value:0 > } was collected before with the same name and label values
        	Test:       	TestServerStatusDataCollector
--- FAIL: TestServerStatusDataCollector (0.05s)
=== RUN   TestTopCollector
--- PASS: TestTopCollector (0.03s)
=== RUN   TestTopologyLabels
--- PASS: TestTopologyLabels (0.16s)
=== RUN   TestGetClusterRole
--- PASS: TestGetClusterRole (0.15s)
=== RUN   TestWalkTo
--- PASS: TestWalkTo (0.00s)
=== RUN   TestMakeLockMetric
--- PASS: TestMakeLockMetric (0.00s)
=== RUN   TestAddLocksMetrics
--- PASS: TestAddLocksMetrics (0.00s)
=== RUN   TestSumMetrics
=== RUN   TestSumMetrics/timeAcquire
=== RUN   TestSumMetrics/timeAcquire#01
--- PASS: TestSumMetrics (0.00s)
    --- PASS: TestSumMetrics/timeAcquire (0.00s)
    --- PASS: TestSumMetrics/timeAcquire#01 (0.00s)
=== RUN   TestCreateOldMetricFromNew
--- PASS: TestCreateOldMetricFromNew (0.00s)
=== RUN   TestMyState
--- PASS: TestMyState (0.03s)
FAIL
FAIL	github.com/percona/mongodb_exporter/exporter	6.141s
=== RUN   TestClientOptionsForDSN
=== RUN   TestClientOptionsForDSN/Escape_username
=== RUN   TestClientOptionsForDSN/Escape_password
--- PASS: TestClientOptionsForDSN (0.00s)
    --- PASS: TestClientOptionsForDSN/Escape_username (0.00s)
    --- PASS: TestClientOptionsForDSN/Escape_password (0.00s)
PASS
ok  	github.com/percona/mongodb_exporter/exporter/dsn_fix	0.012s
=== RUN   TestInspectContainer
--- PASS: TestInspectContainer (0.06s)
PASS
ok  	github.com/percona/mongodb_exporter/internal/tu	0.065s
FAIL
make: *** [Makefile:101: test] Error 1
```

**Comment by a-gavin** [comment]
@tshcherban Do you mind approving the workflow to see if the error persists in the CI pipeline?

**Comment by BupycHuk** [comment]
@a-gavin is this PR still actual? I see that we made changes on auth mechanism which supposed to fix your problem. Could you please take a look?

**Comment by BupycHuk** [comment]
closed PR, because it's outdated

**Pull request closed without merging**
