### PR TITLE
adding databases and collections stats collection

### PR DESCRIPTION
**Pull request by DeathBorn**
from both mongos and mongod side.

### CODE REVIEW

**Comment by dbmurphy** [comment]
This could be rather expensive, and might be a bad item without a way to limit it. Some people have thousands and thousands of names space which will make Prometheus unusable.

**Comment by timvaillancourt** [comment]
I agree with @dbmurphy, this is very expensive. In the dcu/mongodb_exporter this was implemented as an optional flag if I remember correctly. This might be the safer option.

**Comment by AlekSi** [comment]
May you please a PR against `develop` branch?

**Comment by DeathBorn** [comment]
Good insight . I'll rework this accordingly.

**Comment by DeathBorn** [comment]
@AlekSi good.
However, I noticed one bad thing happening with collections metrics. Time to time, I get this error ```was collected before with the same name and label values``` 
. So far, I could not find the reason, why it is happening. it looks like as if exporter can't work with multiple scrapers. Any idea? it happens only with collections metrics.

**Comment by iamanv** [comment]
@DeathBorn How did you run the exporter to be able to export DB metrics for mongod? Running the dbstat command from the exporter always returns an empty document for a dbname. https://github.com/percona/mongodb_exporter/issues/285
Any pointers?

**Pull request closed without merging**
