### PR TITLE
PMM-5609 Update prom client 1.5.1

### PR DESCRIPTION
**Pull request by jacobsin**
with the current 1.0.0 version of prometheus/client_golang, we are seeing the following errors:

```
2020/03/18 15:14:17 http: superfluous response.WriteHeader call from github.com/percona/mongodb_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)
2020/03/18 15:32:01 http: superfluous response.WriteHeader call from github.com/percona/mongodb_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)
```

bumping it seems to have worked for thanos (another prom project):
https://github.com/thanos-io/thanos/issues/1086

bumping to **1.5.1** have worked for mongodb_exporter locally:
https://github.com/prometheus/prometheus/issues/6139

### CODE REVIEW

**Comment by BupycHuk** [comment]
@jacobsin could you add steps to reproduce, please.
Thank you

**Comment by jacobsin** [comment]
@BupycHuk

The way we managed to reproduce it:

1. Have a single-cpu mongo running remotely (in a different data centre/region) to exaggerate the scrape latency.
2. Have a Prometheus with short enough scrape timeout to give up the scrape
3. Check the log of container spinoff percona/mongodb-exporter:latest

Hope this help, am sure you can think of better way to reproduce it too.

**Comment by BupycHuk** [comment]
Thanks a lot, I'll try to reproduce it and check

**Comment by jacobsin** [comment]
@BupycHuk - thanks for the merge. Do we know when will this / `0.11.0` tag be released?

**Pull request merged**
