### PR TITLE
Remove `prometheus/client_golang` replace

### LINKED ISSUE #574: Is the fork of prometheus/client_golang strictly necessary?
**Is your feature request related to a problem? Please describe.**
We are using libraries from mongodb_exporter in our project, and are unable to update from version 0.31.2, since newer versions use the prometheus client at `github.com/Percona-Lab/client_golang` for the custom `MeasureCollectTime` function.

We have other code relying on client_gloang, and have a problem replacing it with that fork. 

- Can the changes in that fork be made official pull requests to client_golang? We could possibly help usher that through if it can be made a standalone request.
- Alternately, can that helper function be refactored into this repo so the client_golang fork is unneeded? 
There may be other solutions, but the goal would be to not need to replace the module for client_golang at all.

### PR DESCRIPTION
**Pull request by marctc**
This PR removes the usage of the custom fork of `prometheus/client_golang` adding `MeasureCollectTime`.
The function is moved to the exporter itself that IMO makes more sense to exist here than the
the instrumentation library.

This would allow us to include last exporter changes with license issues fixed in [grafana agent](https://github.com/grafana/agent/pull/4316).

Fixes #574

- [ ] Links to other linked pull requests (optional).

---

- [ ] Tests passed.
- [ ] Fix conflicts with target branch.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com).

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by marctc** [comment]
We use the lastest version of client_golang and exporter-toolkit. This make some compability issues with the exporter. We can either try to upgrade and fix issues here or downgrade in the agent.

**Review by atymchuk — APPROVED** [review]
@marctc Awesome, thanks for your contribution!

**Comment by atymchuk** [comment]
> We use the lastest version of client_golang and exporter-toolkit in grafana/agent. This make some compability issues with the exporter. We can either try to upgrade and fix issues here or downgrade in grafana/agent.

We will have to discuss internally when we can upgrade to the latest version of `client_golang `, since that has to do with PMM dashboards, that still seem to consume the v1. If it wasn't for supporting v1, we could have gotten rid of it right now.

Thanks anyway!

**Comment by marctc** [comment]
> We will have to discuss internally when we can upgrade to the latest version of `client_golang `, since that has to do with PMM dashboards, that still seem to consume the v1. If it wasn't for supporting v1, we could have gotten rid of it right now.

What does new versions of client_golang have that makes v1 not work?

**Comment by marctc** [comment]
I just bumped `exporter-toolkit` to `v0.10.0` and `client_golang` to `v1.14.0`. With this I can make agent compile and tests here pass. Is this an acceptable solution for you?

**Review by BupycHuk — APPROVED** [review]

**Comment by marctc** [comment]
Thanks again for the fast review @BupycHuk @atymchuk! I just fixed the conflicts in `go.mod` with main.

**Comment by marctc** [comment]
I believe the failing test is flaky. I tried locally and it worked.

**Pull request merged**
