### PR TITLE
adding database and collection stats collection

### PR DESCRIPTION
**Pull request by DeathBorn**
from both mongos and mongod side with an option to enable/disable collection/database metrics

### CODE REVIEW

**Comment by DeathBorn** [comment]
any news?

**Comment by AlekSi** [comment]
I failed to resolve merge conflict in the GitHub UI. Ended up just cherry-picking the commit. Will apply some small fixes in the branch.
Thank you for your contribution! And sorry for a long delay.

**Comment by DeathBorn** [comment]
@AlekSi welcome :) waiting for merge

**Comment by AlekSi** [comment]
See #85.

**Pull request closed without merging**
