### PR TITLE
Build binaries

### PR DESCRIPTION
**Pull request by joshuaspence**
It seems that none of the releases since v0.3.1 include binaries. I'm not sure if this is intentional, but this exporter is much easier to use if I can simply download a precompiled binary directly from GitHub rather than compiling and packaging the exporter myself.

NOTE: I have no idea if the changes made in this pull request will actually fix this issue. I inspect the code changes between v0.3.1 and v0.3.2 and can't see anything obvious which would have resulted in binaries no longer being published. Although, I'm not sure what the release process for this exporter even looks like so it's possible that the maintainers are publishing new versions locally rather than using [Travis](https://docs.travis-ci.com/user/deployment/releases/) and that the omission of binaries was a simple oversight.

### CODE REVIEW

**Comment by adriananeci** [comment]
Any news on binaries build?

**Comment by thaiphv** [comment]
@adriananeci you can try the binaries I built and published on https://github.com/freelancer/mongodb_exporter while waiting for this PR to be reviewed and merged.

**Comment by thaiphv** [comment]
@arvenil do you have any plan for a new release?

**Comment by arvenil** [comment]
@thaiphv This is the only change that ended up in master so far so I was not planning release. Would you like new 0.6.2 release with this or using master would be fine for you?

**Comment by thaiphv** [comment]
@arvenil can you make `0.6.2`?

**Comment by arvenil** [comment]
https://github.com/percona/mongodb_exporter/releases/tag/0.6.2

**Comment by thaiphv** [comment]
@arvenil, thank you.

**Comment by adriananeci** [comment]
@thaiphv Thanks for the build url.
@arvenil Still no binaries in the latest release :(

**Comment by arvenil** [comment]
Hi all, sorry I've misunderstood you. We currently don't provide binaries for our exporters in github. Those exporters are part of bigger project [PMM](https://www.percona.com/software/database-tools/percona-monitoring-and-management) and we have our own build process for that. We may provide those binaries in the future, but we will likely address all our exporter repositories at once. You may also try implementing it on a fork and then make PR https://docs.travis-ci.com/user/deployment/releases/

**Comment by thde** [comment]
Hey @arvenil, I added the Travis steps to deploy the binaries to Github here: https://github.com/percona/mongodb_exporter/pull/125

**Pull request merged**
