### PR TITLE
Chunks per shard per collection

### PR DESCRIPTION
**Pull request by bgriffinte**
This adds a new file to collect chunks per database per shard and export it, gated by a command line option: `--collect.chunkstats` . The collection is not done by default as when there are a large number of chunks this can be a slow metric to collect.

The exported data looks like:
```
# HELP mongodb_mongos_sharding_namespace_shard_chunks The count of chunks per shard per collection
# TYPE mongodb_mongos_sharding_namespace_shard_chunks gauge
mongodb_mongos_sharding_namespace_shard_chunks{namespace="agent.bothways",shard="rs1"} 78
mongodb_mongos_sharding_namespace_shard_chunks{namespace="agent.bothways",shard="rs2"} 79
mongodb_mongos_sharding_namespace_shard_chunks{namespace="agent.ping",shard="rs1"} 1458
mongodb_mongos_sharding_namespace_shard_chunks{namespace="agent.ping",shard="rs2"} 1458
mongodb_mongos_sharding_namespace_shard_chunks{namespace="devicemanager.deviceInterfaces",shard="rs1"} 1350
mongodb_mongos_sharding_namespace_shard_chunks{namespace="devicemanager.deviceInterfaces",shard="rs2"} 1349
```

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/mongodb_exporter?pullRequest=176) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/mongodb_exporter?pullRequest=176) before we can accept your contribution.<br/><hr/>**Benjamin Elijah Griffin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/mongodb_exporter?pullRequest=176) it.</sub>

**Comment by bgriffinte** [comment]
When I check the details on _Pending -- Contributor License Agreement is not signed yet._ I see, and I quote, "**You have signed the CLA for percona/mongodb_exporter**". So why doesn't it update?

**Comment by boagg** [comment]
Hi, 

This PR would be really appreciable on our side :) 

(Especially if there is just SLA to sign)

**Comment by denisok** [comment]
Hello PR owner,

we are cleaning up the mess with the branches. New [mongodb_exporter](https://www.percona.com/blog/2020/09/22/new-mongodb-exporter-released-with-percona-monitoring-and-management-2-10-0/) implementation would be default `main` branch.
Old `master` branch is moved to the `release-0.1x` branch.

Please resubmit and resolve any conflicts against the `main` and we would start to do the better job to get them merged to the `main` and produce regular releases.

We also moved to the Github Actions from Travis CI, so that would check your code going forward.

Thanks,
Denys from Percona

**Comment by denisok** [comment]
`master` branch was renamed to `release-0.1x`.

If you have a local clone, you can update it by running:

git branch -m master release-0.1x
git fetch origin
git branch -u origin/release-0.1x release-0.1x

**Review by percona-csalguero — APPROVED** [review]

**Comment by denisok** [comment]
@boagg we would be happy to land it, please remove conflicts, consider to update new 0.20.x version with this feature instead, that would be maintained version.

**Comment by percona-csalguero** [comment]
Hello @bgriffinte
I am closing this PR since it is outdated and has unsolved conflicts.
If you would likt to talk about it, I can send you an invite to our Percona Community Monthly meeting on discord.
http://per.co.na/discord

Regards

**Pull request closed without merging**
