### PR TITLE
PMM-2632: allow for url-based web listener

### PR DESCRIPTION
**Pull request by davidbirdsong**
now able to listen on a unix sock

### CODE REVIEW

**Comment by arvenil** [comment]
@timvaillancourt Hey, could you take a look? Please ignore for now conflicts, I can deal with that.

**Comment by DexterHD** [comment]
Hi, @davidbirdsong Can you sign the CLA please? And I'll try to resolve conflicts and merge PR.

**Comment by davidbirdsong** [comment]
> Hi, @davidbirdsong Can you sign the CLA please? Also could you review the code and resolve merge conflict in `mongodb_exporter.go`?

done

**Comment by DexterHD** [comment]
> > Hi, @davidbirdsong Can you sign the CLA please? Also could you review the code and resolve merge conflict in `mongodb_exporter.go`?
> 
> done

Are you sure? Maybe you forget to push it? Because I don't see any changes. Also CLA is not signed yet. 😞

https://github.com/percona/mongodb_exporter/pull/95#issuecomment-377663898

**Comment by davidbirdsong** [comment]
I somehow misread this thread while on mobile. I caught that someone else would take care of the merge conflicts and I just needed to sign the CLA (which I thought I'd done.)

I'm not using this anymore and it's been close to a year since my patch, so it'll be awhile before I can carve out time to unravel all the commits since then. Maybe just close it since nobody else has piped up that they wanted it merged in that time frame?

**Comment by davidbirdsong** [comment]
In terms of the CLA, I keep getting to a screen thanking me for signing, but then later says I'm not a github user, which I am.

**Comment by rnovikovP** [comment]
@davidbirdsong  looks like commit made from your  **David Birdsong**  account.  This problem common when person have several accounts and commit and PR from different accounts.

**Comment by davidbirdsong** [comment]
Yeah, I have one account, that's the one.

**Comment by DexterHD** [comment]
> I'm not using this anymore and it's been close to a year since my patch, so it'll be awhile before I can carve out time to unravel all the commits since then. Maybe just close it since nobody else has piped up that they wanted it merged in that time frame?

@davidbirdsong Ok I will close it, because PR was created long time ago and all code which starts the server was moved to https://github.com/percona/exporter_shared. Also I will make a note and maybe I add this feature to **exporter_shared**.

**Pull request closed without merging**
