### PR TITLE
fix invalid memory address, added collect.shardingstatus flag

### PR DESCRIPTION
**Pull request by vrazvan-adobe**
https://jira.percona.com/browse/PMM-6361

- Fix "panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3e758]goroutine 50583 [running]:
github.com/percona/mongodb_exporter/collector/mongos.IsClusterBalanced(0xc000248000, 0xc0005bea80)
/home/travis/gopath/src/github.com/percona/mongodb_exporter/collector/mongos/sharding_status.go:166"

- New flags -collect.shardingstatus can be used to disable Sharding Status . Is enabled by default .

### CODE REVIEW

**Comment by akira-kurogane** [comment]
Thanks Razvan.

I've recommended this patch as you see in https://jira.percona.com/browse/PMM-6361?focusedCommentId=266628&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-266628.

I suggest we rename the option "suppress.shardchunkcount" and that it should be a 'true if present, false if absent' sort of boolean option like the other --collect.* options. "True", "false", "False", 1, 0,  "1", "off", "on", "enabled", "disabled", "" will all evaluate as false with this commit.

**Comment by vrazvan-adobe** [comment]
I've made the change suggested by Akira Kurogane

**Comment by akira-kurogane** [comment]
Hi Razvan.

Sorry, I didn't mean to trouble you to do that! I intended the option name suggestion for Roma or Carlos in the PMM team whose I was writing the same things into slack in parallel.

We're going in parallel at the moment. I think I'm spending more time on ticket comments than programming or team communication. From yesterday the PMM team was in favour of doing it, and it's been communication back-and-forth since then.  Multiple teams, some lag is inevitable.

**Comment by vrazvan-adobe** [comment]
Hi Akira,

It wasn't a big deal, it took me only 10 minutes to make suggested changes and functionality tests .

**Comment by percona-csalguero** [comment]
Could you please fix tests?

**Comment by vrazvan-adobe** [comment]
I've figure it out what is needed for travis check to pass. I've added updated help output file.

**Comment by vrazvan-adobe** [comment]
Is ok now ?

**Comment by vrazvan-adobe** [comment]
Is something else needed for this PR ?

**Comment by akira-kurogane** [comment]
Hi @vrazvan-adobe. Thanks for filling in the CLA and the last commit that addressed the Travis build failure error.

You won't need to do anything else for this PR. The technical issues the "CodeCov" report mentions are not caused by your patch.

I'll ask that this be merged tonight.

**Comment by vrazvan-adobe** [comment]
Hi @akira-kurogane, 

Thank you for confirming that everything is ok . I hope that it will be merged soon.

**Comment by vrazvan-adobe** [comment]
All but CodeCov checks have succeeded 5 days ago. I understood that issues the "CodeCov" report mentions are not caused by this patch. Something else need to be done for this to be merged ?

**Review by percona-csalguero — APPROVED** [review]

**Pull request merged**
